enum dataLines{
    HIGH_SCORE = 0,
    HERO_POSITION_SAVE = 1,
    SCORE_SAVE = 2,
    LEVEL_SAVE = 3,
    GROUND_OBSTACLES_POSITIONS_SAVE = 4,
    FLYING_OBSTACLES_POSITIONS_SAVE = 5,
    BUSHES_POSITIONS_SAVE = 6,
    IS_ROBOT_SAVE = 7,
    ZOMBIE_POSITION_SAVE = 8,
    IS_ENEMY_NINJA_SAVE = 9,
};